Aquarius/Site/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', index),
    path('Application/', form, name='app'),
]

Aquarius/Site/models.py
from django.db import models

# Create your models here.

Aquarius/Site/forms.py
from django import forms

class ApplicationForm(forms.Form):
    name = forms.CharField(label="Name", max_length=100)
    phone_number = forms.CharField(label="Phone number", max_length=100)
    address = forms.CharField(label="Delivery address", max_length=100)
    comment = forms.CharField(label="Comment or message", max_length=100)

Aquarius/Site/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from Site.forms import *

# Create your views here.

def index(request):
    return render(request, 'aquarius/content.html')

def form(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = ApplicationForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            successForm = form.cleaned_data
            print(str(successForm))
            return HttpResponse("Sent successfully!")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ApplicationForm()

    return render(request, 'aquarius/application_form.html', {"form": form})

Aquarius/Site/templates/aquarius/application_form.html
{% extends "aquarius/base.html" %}

{% block title %}Order{% endblock %}

{% block content %}
  <div class="mx-80">
    <h1 class="text-3xl font-bold">
      Fill the form!
    </h1>

    <form action="" method="post">
      {% csrf_token %}
      <div class="space-y-12">
        <div class="border-b">
          <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
            <div class="sm:col-span-4">
              <label class="block text-sm font-medium leading-6">{{form.name.label}}</label>
              <div class="mt-2">
                <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md pl-3">
                  <input type="text" required id="id_name" name="name" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-white placeholder:text-white focus:ring-0 sm:text-sm sm:leading-6 p-1" placeholder="Enter a name">
                </div>
              </div>
            </div>

            <div class="sm:col-span-4">
              <label class="block text-sm font-medium leading-6">{{form.phone_number.label}}</label>
              <div class="mt-2">
                <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                  <span class="flex select-none items-center pl-3 text-blue-900 sm:text-sm">+7 </span>
                  <input type="text" required id="id_phone_number" name="phone_number" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-white placeholder:text-white focus:ring-0 sm:text-sm sm:leading-6 p-1" placeholder="(***)-***-**-**">
                </div>
              </div>
            </div>

            <div class="sm:col-span-4">
              <label class="block text-sm font-medium leading-6">{{form.address.label}}</label>
              <div class="mt-2">
                <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md pl-3">
                  <input type="text" required id="id_address" name="address" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-white placeholder:text-white focus:ring-0 sm:text-sm sm:leading-6 p-1" placeholder="Enter the delivery address">
                </div>
              </div>
            </div>

            <div class="col-span-full">
              <label class="block text-sm font-medium leading-6">{{form.comment.label}}</label>
              <div class="mt-2">
                <textarea required id="id_comment" name="comment" rows="3" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 pl-3" placeholder="The amount of water, for example"></textarea>
              </div>
            </div>
          </div>
        </div>

        <div class="mt-6 flex items-center gap-x-6">
          <button type="submit" class="rounded-md bg-blue-800 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-blue-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Submit</button>
        </div>
      </div>
    </form>

  </div>

{% endblock %}

Aquarius/Site/templates/aquarius/base.html
{% load static %}
<!--{% load tailwind_tags %} Можно отключить если 7 строка включена!-->
<!DOCTYPE html>
<html lang="en" class="bg-gradient-to-r from-cyan-500 to-blue-500 text-white mt-16">
<head>
    <link rel="shortcut icon" type="image/jpg" href="{% static 'aquarius/images/croppedaqua.jpg' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'aquarius/css/output.css' %}" >
    <meta charset="UTF-8">
<!--    <script src="https://cdn.tailwindcss.com"></script>-->
    <title>{% block title %}{% endblock %}</title>
<!--    {% tailwind_css %} Можно отключить если 7 строка включена!-->
</head>
{% if request.path == '/' %}
    {% include "aquarius/header.html" %}
{% endif %}

<body>
{% block content %}
{% endblock %}
</body>
{% if request.path == '/' %}
    {% include "aquarius/footer.html" %}
{% endif %}

</html>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
<script src="{% static 'aquarius/js/script.js' %}"></script>

Aquarius/Site/templates/aquarius/footer.html
{% load static %}
<footer id="contacts" class="text-white w-auto h-auto mx-16">
    <div class="bg-blue-700 flex rounded-[32px]">
        <div class="w-3/6 grid justify-items-center">
            <img class="rounded-[32px]" src="{% static 'aquarius/images/water_delivery.svg' %}">
        </div>
        <div class="w-3/6 grid justify-items-center p-12 items-center">
            <h1 class="text-4xl font-bold">Our contacts</h1>
            <ul class="space-y-2">
                <p class="text-2xl">You can contact us via:</p>
                <li class="flex space-x-4">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                    <path fill-rule="evenodd" d="M1.5 4.5a3 3 0 013-3h1.372c.86 0 1.61.586 1.819 1.42l1.105 4.423a1.875 1.875 0 01-.694 1.955l-1.293.97c-.135.101-.164.249-.126.352a11.285 11.285 0 006.697 6.697c.103.038.25.009.352-.126l.97-1.293a1.875 1.875 0 011.955-.694l4.423 1.105c.834.209 1.42.959 1.42 1.82V19.5a3 3 0 01-3 3h-2.25C8.552 22.5 1.5 15.448 1.5 6.75V4.5z" clip-rule="evenodd" />
                    </svg>
                    <p>+7 XXXX XX XX XX</p>
                </li>
                <li class="flex space-x-4">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                    <path d="M10.5 18.75a.75.75 0 000 1.5h3a.75.75 0 000-1.5h-3z" />
                    <path fill-rule="evenodd" d="M8.625.75A3.375 3.375 0 005.25 4.125v15.75a3.375 3.375 0 003.375 3.375h6.75a3.375 3.375 0 003.375-3.375V4.125A3.375 3.375 0 0015.375.75h-6.75zM7.5 4.125C7.5 3.504 8.004 3 8.625 3H9.75v.375c0 .621.504 1.125 1.125 1.125h2.25c.621 0 1.125-.504 1.125-1.125V3h1.125c.621 0 1.125.504 1.125 1.125v15.75c0 .621-.504 1.125-1.125 1.125h-6.75A1.125 1.125 0 017.5 19.875V4.125z" clip-rule="evenodd" />
                    </svg>
                    <p>+7 XXX XXX XX XX</p>
                </li>
                <li class="flex space-x-4">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                    <path d="M1.5 8.67v8.58a3 3 0 003 3h15a3 3 0 003-3V8.67l-8.928 5.493a3 3 0 01-3.144 0L1.5 8.67z" />
                    <path d="M22.5 6.908V6.75a3 3 0 00-3-3h-15a3 3 0 00-3 3v.158l9.714 5.978a1.5 1.5 0 001.572 0L22.5 6.908z" />
                    </svg>
                    <p>lorem.ipsum@fishmail.com</p>
                </li>
                <li class="flex space-x-4">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                    <path d="M11.47 3.84a.75.75 0 011.06 0l8.69 8.69a.75.75 0 101.06-1.06l-8.689-8.69a2.25 2.25 0 00-3.182 0l-8.69 8.69a.75.75 0 001.061 1.06l8.69-8.69z" />
                    <path d="M12 5.432l8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 01-.75-.75v-4.5a.75.75 0 00-.75-.75h-3a.75.75 0 00-.75.75V21a.75.75 0 01-.75.75H5.625a1.875 1.875 0 01-1.875-1.875v-6.198a2.29 2.29 0 00.091-.086L12 5.43z" />
                    </svg>
                    <p>1st Office, Lorem</p>
                </li>
                <li class="flex space-x-4">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                    <path d="M11.47 3.84a.75.75 0 011.06 0l8.69 8.69a.75.75 0 101.06-1.06l-8.689-8.69a2.25 2.25 0 00-3.182 0l-8.69 8.69a.75.75 0 001.061 1.06l8.69-8.69z" />
                    <path d="M12 5.432l8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 01-.75-.75v-4.5a.75.75 0 00-.75-.75h-3a.75.75 0 00-.75.75V21a.75.75 0 01-.75.75H5.625a1.875 1.875 0 01-1.875-1.875v-6.198a2.29 2.29 0 00.091-.086L12 5.43z" />
                    </svg>
                    <p>2nd Office, Ipsum</p>
                </li>
            </ul>
            <p class="text-xl">Water delivery is carried out daily!</p>
            <div class="flex space-x-4">
                <a href="https://wa.me/" class="bg-green-500 rounded-full p-4 font-bold hover:transition hover:duration-300 hover:bg-white hover:text-green-500">Go to WhatsApp</a>
                <a href="{% url 'app' %}" class="bg-blue-800 rounded-full p-4 font-bold hover:transition hover:duration-300 hover:bg-white hover:text-blue-800">Make order</a>
            </div>

        </div>
    </div>
</footer>

Aquarius/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>